# Generated by Django 2.0.4 on 2018-04-14 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysisApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='screen_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
