# Generated by Django 2.0.4 on 2018-04-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisApp', '0002_auto_20180414_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
