# Generated by Django 2.0.4 on 2018-04-14 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysisApp', '0003_auto_20180414_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('screen_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('oauth_token', models.CharField(max_length=200)),
                ('oauth_secret', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
